---
- name: Add Docker GPG key
  become: yes
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of packages
  become: yes
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
    state: present
    update_cache: yes
