---
- name: Create the user 'k8s'
  become: yes
  user:
    name: k8s
    state: present
    group: docker
    shell: /bin/bash
- name: Add authorized key
  become: yes
  become_user: k8s
  authorized_key:
    user: k8s
    state: present
    key: "{{ lookup('file', '../id_rsa.pub' ) }}"
